# Importing the required libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('heart.csv')

In [3]:
df.head()

   age  sex   BP  cholestrol  heart disease
0   70    1  130         322              1
1   67    0  115         564              0
2   57    1  124         261              1
3   64    1  128         263              0
4   74    0  120         269              0

In [4]:
df.shape

(270, 5)

In [5]:
df.columns

Index(['age', 'sex', 'BP', 'cholestrol', 'heart disease'], dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            270 non-null    int64
 1   sex            270 non-null    int64
 2   BP             270 non-null    int64
 3   cholestrol     270 non-null    int64
 4   heart disease  270 non-null    int64
dtypes: int64(5)
memory usage: 10.7 KB

In [7]:
df.describe()

              age         sex          BP  cholestrol  heart disease
count  270.000000  270.000000  270.000000  270.000000     270.000000
mean    54.433333    0.677778  131.344444  249.659259       0.444444
std      9.109067    0.468195   17.861608   51.686237       0.497827
min     29.000000    0.000000   94.000000  126.000000       0.000000
25%     48.000000    0.000000  120.000000  213.000000       0.000000
50%     55.000000    1.000000  130.000000  245.000000       0.000000
75%     61.000000    1.000000  140.000000  280.000000       1.000000
max     77.000000    1.000000  200.000000  564.000000       1.000000

# Putting Feature Variable to X and Target variable to y.

In [8]:
# Putting feature variable to X
X = df.drop('heart disease',axis=1)
# Putting response variable to y
y = df['heart disease']

# Train-Test-Split is performed

In [9]:
# now lets split the data into train and test
from sklearn.model_selection import train_test_split
# Splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42)
X_train.shape, X_test.shape

((189, 4), (81, 4))

# Let’s import RandomForestClassifier and fit the data.

In [10]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5,
                                       n_estimators=100, oob_score=True)
#%%time
classifier_rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [11]:
# checking the oob score
classifier_rf.oob_score_

0.656084656084656

## Let’s do hyperparameter tuning for Random Forest using GridSearchCV and fit the data.

In [12]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)
params = {
    'max_depth': [2,3,5,10,20],
    'min_samples_leaf': [5,10,20,50,100,200],
    'n_estimators': [10,25,30,50,100,200]
}
from sklearn.model_selection import GridSearchCV
# Instantiate the grid search model
grid_search = GridSearchCV(estimator=rf,
                           param_grid=params,
                           cv = 4,
                           n_jobs=-1, verbose=1, scoring="accuracy")
#%%time
grid_search.fit(X_train, y_train)

Fitting 4 folds for each of 180 candidates, totalling 720 fits

GridSearchCV(cv=4, estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [2, 3, 5, 10, 20],
                         'min_samples_leaf': [5, 10, 20, 50, 100, 200],
                         'n_estimators': [10, 25, 30, 50, 100, 200]},
             scoring='accuracy', verbose=1)

In [13]:
grid_search.best_score_

0.6985815602836879

In [14]:
rf_best = grid_search.best_estimator_
rf_best

RandomForestClassifier(max_depth=5, min_samples_leaf=10, n_estimators=10,
                       n_jobs=-1, random_state=42)

## Now, let’s visualize

In [15]:
from sklearn.tree import plot_tree
plt.figure(figsize=(80,40))
plot_tree(rf_best.estimators_[5], feature_names = X.columns,class_names=['Disease', "No Disease"],filled=True);

InvalidParameterError: The 'feature_names' parameter of plot_tree must be an instance of 'list' or None. Got Index(['age', 'sex', 'BP', 'cholestrol'], dtype='object') instead.

In [16]:
!pip install -U scikit-learn

Requirement already satisfied: scikit-learn in d:\anaconda\lib\site-packages (1.3.0)
Collecting scikit-learn
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/79/3d/02d5d3ed359498fec3abdf65407d3c07e3b8765af17464969055aaec5171/scikit_learn-1.4.2-cp311-cp311-win_amd64.whl.metadata
  Downloading scikit_learn-1.4.2-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.19.5 in d:\anaconda\lib\site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: scipy>=1.6.0 in d:\anaconda\lib\site-packages (from scikit-learn) (1.11.1)
Requirement already satisfied: joblib>=1.2.0 in d:\anaconda\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\anaconda\lib\site-packages (from scikit-learn) (2.2.0)
Downloading scikit_learn-1.4.2-cp311-cp311-win_amd64.whl (10.6 MB)
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB 1.4 MB/s eta 0:00:08
    --------------------------------------- 0.2/10.6 MB 1.8 MB/s eta 0:00:06
   - -------------------------------------- 0.5/10.6 MB 3.5 MB/s eta 0:00:03
   --- ------------------------------------ 0.8/10.6 MB 5.4 MB/s eta 0:00:02
   ----- ---------------------------------- 1.4/10.6 MB 6.2 MB/s eta 0:00:02
   ------ --------------------------------- 1.8/10.6 MB 6.8 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/10.6 MB 7.6 MB/s eta 0:00:02
   ----------- ---------------------------- 3.0/10.6 MB 8.2 MB/s eta 0:00:01
   ------------- -------------------------- 3.5/10.6 MB 8.7 MB/s eta 0:00:01
   --------------- ------------------------ 4.1/10.6 MB 9.1 MB/s eta 0:00:01
   --------------- ------------------------ 4.2/10.6 MB 9.0 MB/s eta 0:00:01
   ----------------- ---------------------- 4.5/10.6 MB 8.3 MB/s eta 0:00:01
   ----------------- ---------------------- 4.5/10.6 MB 8.3 MB/s eta 0:00:01
   ------------------ --------------------- 4.8/10.6 MB 7.7 MB/s eta 0:00:01
   ------------------ --------------------- 4.8/10.6 MB 7.7 MB/s eta 0:00:01
   ------------------ --------------------- 4.8/10.6 MB 7.7 MB/s eta 0:00:01
   ------------------ --------------------- 4.8/10.6 MB 7.7 MB/s eta 0:00:01
   ------------------ --------------------- 4.8/10.6 MB 7.7 MB/s eta 0:00:01
   ------------------ --------------------- 5.0/10.6 MB 5.6 MB/s eta 0:00:02
   --------------------- ------------------ 5.6/10.6 MB 6.0 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.2 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.2 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.2 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.2 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.2 MB/s eta 0:00:01
   ---------------------- ----------------- 5.9/10.6 MB 6.2 MB/s eta 0:00:01
   ------------------------ --------------- 6.5/10.6 MB 5.1 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 5.4 MB/s eta 0:00:01
   -------------------------- ------------- 7.1/10.6 MB 5.4 MB/s eta 0:00:01
   ---------------------------- ----------- 7.5/10.6 MB 4.7 MB/s eta 0:00:01
   ------------------------------ --------- 8.0/10.6 MB 4.8 MB/s eta 0:00:01
   ------------------------------- -------- 8.2/10.6 MB 4.9 MB/s eta 0:00:01
   -------------------------------- ------- 8.5/10.6 MB 4.9 MB/s eta 0:00:01
   -------------------------------- ------- 8.7/10.6 MB 4.8 MB/s eta 0:00:01
   -------------------------------- ------- 8.7/10.6 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.6 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.6 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.6 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.6 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------------- ----- 9.1/10.6 MB 4.3 MB/s eta 0:00:01
   ------------------------------------ --- 9.7/10.6 MB 4.4 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.6 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.6 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.6 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.6 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.6 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 10.1/10.6 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 4.2 MB/s eta 0:00:00
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.3.0
    Uninstalling scikit-learn-1.3.0:
      Successfully uninstalled scikit-learn-1.3.0

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\anaconda\\Lib\\site-packages\\~klearn\\cluster\\_dbscan_inner.cp311-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

In [17]:
from sklearn.tree import plot_tree
plt.figure(figsize=(80,40))
plot_tree(rf_best.estimators_[7], feature_names = X.columns,class_names=['Disease', "No Disease"],filled=True);

InvalidParameterError: The 'feature_names' parameter of plot_tree must be an instance of 'list' or None. Got Index(['age', 'sex', 'BP', 'cholestrol'], dtype='object') instead.

### The trees created by estimators_[5] and estimators_[7] are different. Thus we can say that each tree is independent of the other.

### Now let’s sort the data with the help of feature importance

In [18]:
rf_best.feature_importances_

array([0.46128487, 0.2180848 , 0.13174619, 0.18888413])

In [19]:
## feature importance

imp_df = pd.DataFrame({
    "Varname": X_train.columns,
    "Imp": rf_best.feature_importances_
})

In [20]:
imp_df.sort_values(by="Imp", ascending=False)

      Varname       Imp
0         age  0.461285
1         sex  0.218085
3  cholestrol  0.188884
2          BP  0.131746